# Generated by Django 4.2 on 2023-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('demand', models.IntegerField()),
                ('size', models.CharField(choices=[('5M', '5 Marla'), ('8M', '8 Marla'), ('13M', '10 Marla'), ('1K', '1 Kanal'), ('2K', '2 Kanal')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
