# Generated by Django 4.2 on 2023-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPosts', '0002_posts_user_posts_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sector',
            field=models.CharField(choices=[('A', 'Sector A'), ('B', 'Sector B'), ('B1', 'Sector B1'), ('B2', 'Sector B2'), ('C', 'Sector C'), ('C1', 'Sector C1'), ('C2', 'Sector C2'), ('C3', 'Sector C3'), ('D', 'Sector D'), ('E', 'Sector E'), ('F', 'Sector F'), ('F1', 'Sector F1'), ('G', 'Sector G'), ('H', 'Sector H'), ('I', 'Sector I'), ('J', 'Sector J'), ('K', 'Sector K'), ('L', 'Sector L'), ('M', 'Sector M'), ('N', 'Sector N'), ('O', 'Sector O'), ('P', 'Sector P')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='size',
            field=models.CharField(choices=[('4M', '4 Marla'), ('5M', '5 Marla'), ('8M', '8 Marla'), ('10M', '10 Marla'), ('1K', '1 Kanal'), ('2K', '2 Kanal')], max_length=3),
        ),
    ]
