# Generated by Django 4.2 on 2023-05-02 07:40

from django.db import migrations, models
import django.db.models.deletion
import myPosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('myPosts', '0003_posts_sector_posts_type_alter_posts_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='size',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='type',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myPosts.models.get_image_filename, verbose_name='images')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myPosts.posts')),
            ],
        ),
    ]
