# Generated by Django 4.2 on 2023-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPosts', '0005_posts_sector_posts_size_posts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='viewed',
            field=models.CharField(default='0', editable=False, max_length=7),
        ),
    ]
