# Generated by Django 4.2 on 2023-05-01 14:47

from django.db import migrations, models
import myStore.models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts_1',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='posts_1',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='images_1',
            name='image',
            field=models.ImageField(upload_to=myStore.models.get_image_filename, verbose_name='Image_1'),
        ),
    ]
