# Generated by Django 4.2 on 2023-05-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0002_remove_posts_1_demand_remove_posts_1_viewed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_1',
            old_name='ad_id',
            new_name='post_id',
        ),
    ]
